name: Lint Codebase on Push
on:
  push:
    branches-ignore: ["main"]

jobs:
  build:
    name: Pylint Check
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:

    - name: Checkout code
      uses: actions/checkout@main
      with:
        fetch-depth: 0

    - name: Linting
      uses: super-linter/super-linter@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_ALL_CODEBASE: false
        VALIDATE_PYTHON_FLAKE8: true
        IGNORE_GITIGNORED_FILES: true
        LINTER_RULES_PATH: .github/linters
        
